### ISSUE TITLE
Issue with potion preventing

### ISSUE THREAD

**Issue by NathanWolf** [elBukkit/PreciousStones#1]
I have a problem, when I didn't set any flag to prevent potions, the negative effect potions aren't working on my field, only positive effect potions are working.

**Comment by xtomyserrax** [comment]
I would need to see the flags the player applied to the field. I mean if he is using Peace Keeper, then yeah, as it prevents pvp it will prevent the damage caused by a splash potion even though there is no prevent potions flag, I guess that is intended.

I tested for example in a regular field without prevent-pvp and potion damage works perfectly fine, we need the config file to test this.
