### ISSUE TITLE
Question about switchable flag setting

### ISSUE THREAD

**Issue by Axer22** [elBukkit/PreciousStones#11]
Can I set default flag setting on false?

**Comment by xtomyserrax** [comment]
You mean toggeable flags? (the ones starting with ?). If you mean those ones Im not 100% sure, but I guess you should be able, I will check that

I found out that you cant make prevent-use list flag toggeable, at least I couldnt and its something I would like for people to change

**Comment by Axer22** [comment]
Yes, I tried "?prevent-entry: false" but it isn't working.

**Comment by xtomyserrax** [comment]
Hmm let me check that and see if it can be fixed, ty!

**Comment by xtomyserrax** [comment]
Yes, plugin doesnt recognize the false there. Will see if I can fix that (if possible)

**Comment by xtomyserrax** [comment]
Okay so the actual logic of the plugin here works like this: any flag you add if you set it to true it means the flag will be added to the field, if false, it means it wont.

So this same logic happens with toggeable, if true it is going to add it, if false, it is not. So its a kind of enable/disable system so you dont need to remove it from the list. 

Maybe we can use "?" for toggeable flags which will enable it for default, and "¿" for toggeable flags that will be disabled for default. What do you guys think? Do you have a better idea?

It wouldnt be wise to change the system as it would break support for older configurations and because also setting the flag to false only has sense in toggeable ones. Or maybe I could change the system to only care about that false boolean in toggeable situations, I will see what I can do there!

**Comment by xtomyserrax** [comment]
So I wasnt understandting how flags work. Let me explain:
- prevent-place:true (means that the prevent-place flag will be added for default to the field, that means when a field is created the flag will be enabled. The flag is also toggeable, so players can disable it)
- ?prevent-break:true (means that the prevent-break flag will be added for default to false to the field, but it is toggeable, so players can change it to true)

What does the false mean? It works exactly as removing the flag from the list, it means that the flag will be ignored.

Let me know if you understood it or have any other question, if not, close the issue please!

Took me some time to understand how the code was working, maybe the word "toggeable" for "?" flags leads to confussion.
