### ISSUE TITLE
Command allow/remove Question

### ISSUE THREAD

**Issue by durajg01** [elBukkit/PreciousStones#91]
Hello, can I find out what is the difference between "guest" and "co-owner" in the ps allow command?
And is there a list of what changes have been made to the plug?

**Comment by xtomyserrax** [comment]
Hey! Guest and Co-Owner have existed since the start. The main difference is that a guest cant destroy or place new fields inside the field he is a guest, but a co-owner can do those things and also he is able to invite new players.

This are the actual ways to see changes made:
* Each update is sent with a Pull Request, so you can check closed ones: https://github.com/elBukkit/PreciousStones/pulls?q=is%3Apr+is%3Aclosed
* When you download an update, it has a list of changes which can send you to the Pull Request that made it: https://jenkins.elmakers.com/job/PreciousStones/56/
